# Generated by Django 4.2.29 on 2026-05-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConnecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du connecteur')),
                ('vitesse_charge', models.CharField(choices=[('standard', 'Standard'), ('rapide', 'Rapide')], default='standard', max_length=20, verbose_name='Vitesse de charge')),
            ],
            options={
                'verbose_name': 'Type de connecteur',
                'verbose_name_plural': 'Types de connecteurs',
            },
        ),
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=30, unique=True, verbose_name='Identifiant')),
                ('emplacement', models.CharField(max_length=200, verbose_name='Emplacement / Adresse')),
                ('ville', models.CharField(default='', max_length=100, verbose_name='Ville')),
                ('puissance_kw', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Puissance (kW)')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('maintenance', 'En maintenance')], default='libre', max_length=20, verbose_name='Statut')),
                ('date_installation', models.DateField(verbose_name="Date d'installation")),
                ('type_connecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bornes.typeconnecteur', verbose_name='Type de connecteur')),
            ],
            options={
                'verbose_name': 'Borne de recharge',
                'verbose_name_plural': 'Bornes de recharge',
                'ordering': ['identifiant'],
            },
        ),
    ]
