# Generated by Django 4.2.29 on 2026-05-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bornes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('duree_minutes', models.PositiveIntegerField(verbose_name='Durée (minutes)')),
                ('energie_kwh', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Énergie délivrée (kWh)')),
                ('borne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bornes.borne', verbose_name='Borne')),
            ],
            options={
                'verbose_name': 'Session de charge',
                'verbose_name_plural': 'Sessions de charge',
                'ordering': ['-date_debut'],
            },
        ),
    ]
