# Generated by Django 4.2.29 on 2026-05-11 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bornes', '0002_sessioncharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borne',
            options={'ordering': ['identifiant'], 'permissions': [('can_manage_maintenance', 'Peut gérer les opérations de maintenance')], 'verbose_name': 'Borne de recharge', 'verbose_name_plural': 'Bornes de recharge'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('technicien', 'Technicien de maintenance'), ('gestionnaire', 'Gestionnaire de réseau')], default='technicien', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
