# Generated by Django 4.2.29 on 2026-05-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bornes', '0003_alter_borne_options_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borne',
            options={'ordering': ['identifiant'], 'verbose_name': 'Borne de recharge', 'verbose_name_plural': 'Bornes de recharge'},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
